# This file is managed by 'repo_helper'.
# You may add new sections, but any changes made to the following sections will be lost:
#     * tox
#     * envlists
#     * testenv
#     * testenv:.package
#     * testenv:py313-dev
#     * testenv:py313
#     * testenv:py312-dev
#     * testenv:py312
#     * testenv:docs
#     * testenv:build
#     * testenv:lint
#     * testenv:perflint
#     * testenv:mypy
#     * testenv:pyup
#     * flake8
#     * check-wheel-contents
#     * pytest

[tox]
envlist = py36, docs
skip_missing_interpreters = True
isolated_build = True
requires =
    pip>=21,!=22.2
    tox-envlist>=0.2.1
    tox~=3.0
    virtualenv!=20.16.0,<20.39


[testenv]
setenv =
    PYTHONDEVMODE=1
    PIP_DISABLE_PIP_VERSION_CHECK=1
    SETUPTOOLS_USE_DISTUTILS=stdlib
download = True
deps = importcheck>=0.1.0
commands =
    python --version
    python -m importcheck {posargs:--show}

[testenv:.package]
setenv =
    PYTHONDEVMODE=1
    PIP_DISABLE_PIP_VERSION_CHECK=1

[testenv:docs]
setenv = SHOW_TODOS = 1
skip_install = true
passenv = SPHINX_BUILDER
basepython = python3.8
changedir = {toxinidir}/source
deps = -r{toxinidir}/source/requirements.txt
commands = sphinx-build -M {env:SPHINX_BUILDER:html} . ./build {posargs}

